//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APDBEntities : DbContext
    {
        public APDBEntities()
            : base("name=APDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyDetail> CompanyDetail { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<OrderTransaction> OrderTransaction { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<WorkSheet> WorkSheet { get; set; }
    
        public virtual ObjectResult<usp_GetCompany_Result> usp_GetCompany(Nullable<int> companyId, string flag)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCompany_Result>("usp_GetCompany", companyIdParameter, flagParameter);
        }
    
        public virtual ObjectResult<usp_GetCompanyDashboard_Result> usp_GetCompanyDashboard(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCompanyDashboard_Result>("usp_GetCompanyDashboard", companyIdParameter);
        }
    
        public virtual ObjectResult<usp_GetCompanyProduct_Result> usp_GetCompanyProduct(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCompanyProduct_Result>("usp_GetCompanyProduct", companyIdParameter);
        }
    
        public virtual ObjectResult<usp_GetDashboard_Result> usp_GetDashboard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDashboard_Result>("usp_GetDashboard");
        }
    
        public virtual ObjectResult<usp_GetOrder_Result> usp_GetOrder(Nullable<int> orderID, string flag, Nullable<int> orderType, Nullable<int> orderStatus, Nullable<bool> isPaid, Nullable<int> companyId)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var orderTypeParameter = orderType.HasValue ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(int));
    
            var orderStatusParameter = orderStatus.HasValue ?
                new ObjectParameter("OrderStatus", orderStatus) :
                new ObjectParameter("OrderStatus", typeof(int));
    
            var isPaidParameter = isPaid.HasValue ?
                new ObjectParameter("IsPaid", isPaid) :
                new ObjectParameter("IsPaid", typeof(bool));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrder_Result>("usp_GetOrder", orderIDParameter, flagParameter, orderTypeParameter, orderStatusParameter, isPaidParameter, companyIdParameter);
        }
    
        public virtual ObjectResult<usp_GetOrderDetail_Result> usp_GetOrderDetail(Nullable<int> orderID, string flag)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderDetail_Result>("usp_GetOrderDetail", orderIDParameter, flagParameter);
        }
    
        public virtual ObjectResult<usp_GetOrderTransaction_Result> usp_GetOrderTransaction(Nullable<int> orderID, Nullable<int> orderDetailID, string flag)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var orderDetailIDParameter = orderDetailID.HasValue ?
                new ObjectParameter("OrderDetailID", orderDetailID) :
                new ObjectParameter("OrderDetailID", typeof(int));
    
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderTransaction_Result>("usp_GetOrderTransaction", orderIDParameter, orderDetailIDParameter, flagParameter);
        }
    
        public virtual ObjectResult<usp_GetProduct_Result> usp_GetProduct(string flag, Nullable<int> productID, Nullable<int> productTypeId, string productTypeName)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var productTypeIdParameter = productTypeId.HasValue ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(int));
    
            var productTypeNameParameter = productTypeName != null ?
                new ObjectParameter("ProductTypeName", productTypeName) :
                new ObjectParameter("ProductTypeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProduct_Result>("usp_GetProduct", flagParameter, productIDParameter, productTypeIdParameter, productTypeNameParameter);
        }
    
        public virtual ObjectResult<usp_GetProductType_Result> usp_GetProductType(string flag, Nullable<int> productTypeId, string type, string productTypeName)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var productTypeIdParameter = productTypeId.HasValue ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var productTypeNameParameter = productTypeName != null ?
                new ObjectParameter("ProductTypeName", productTypeName) :
                new ObjectParameter("ProductTypeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProductType_Result>("usp_GetProductType", flagParameter, productTypeIdParameter, typeParameter, productTypeNameParameter);
        }
    
        public virtual ObjectResult<usp_GetWorkSheet_Result> usp_GetWorkSheet(string flag, Nullable<int> workId, string date, Nullable<int> companyId, string description, Nullable<int> status)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var workIdParameter = workId.HasValue ?
                new ObjectParameter("WorkId", workId) :
                new ObjectParameter("WorkId", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetWorkSheet_Result>("usp_GetWorkSheet", flagParameter, workIdParameter, dateParameter, companyIdParameter, descriptionParameter, statusParameter);
        }
    
        public virtual int usp_ImportCompanyDetail(Nullable<int> createdby)
        {
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportCompanyDetail", createdbyParameter);
        }
    
        public virtual int usp_InsertUpdateCompanyDetail(string flag, Nullable<int> companyId, string companyName, string companyAddress, string companycountry, string companyState, string companyPinCode, string companyPhone, string companyEmail, string companyGST, string contactPersonName, Nullable<int> createdBy)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var companyAddressParameter = companyAddress != null ?
                new ObjectParameter("CompanyAddress", companyAddress) :
                new ObjectParameter("CompanyAddress", typeof(string));
    
            var companycountryParameter = companycountry != null ?
                new ObjectParameter("Companycountry", companycountry) :
                new ObjectParameter("Companycountry", typeof(string));
    
            var companyStateParameter = companyState != null ?
                new ObjectParameter("CompanyState", companyState) :
                new ObjectParameter("CompanyState", typeof(string));
    
            var companyPinCodeParameter = companyPinCode != null ?
                new ObjectParameter("CompanyPinCode", companyPinCode) :
                new ObjectParameter("CompanyPinCode", typeof(string));
    
            var companyPhoneParameter = companyPhone != null ?
                new ObjectParameter("CompanyPhone", companyPhone) :
                new ObjectParameter("CompanyPhone", typeof(string));
    
            var companyEmailParameter = companyEmail != null ?
                new ObjectParameter("CompanyEmail", companyEmail) :
                new ObjectParameter("CompanyEmail", typeof(string));
    
            var companyGSTParameter = companyGST != null ?
                new ObjectParameter("CompanyGST", companyGST) :
                new ObjectParameter("CompanyGST", typeof(string));
    
            var contactPersonNameParameter = contactPersonName != null ?
                new ObjectParameter("ContactPersonName", contactPersonName) :
                new ObjectParameter("ContactPersonName", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertUpdateCompanyDetail", flagParameter, companyIdParameter, companyNameParameter, companyAddressParameter, companycountryParameter, companyStateParameter, companyPinCodeParameter, companyPhoneParameter, companyEmailParameter, companyGSTParameter, contactPersonNameParameter, createdByParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_InsertUpdateOrder(string flag, Nullable<int> companyId, Nullable<int> orderID, string orderDate, Nullable<int> orderType, string diliveryTime, Nullable<int> totalAmount, Nullable<int> totalDue, string orderNo, string shipVia, Nullable<int> gSTApply, string orderComments, Nullable<int> freightcharge, Nullable<int> orderStatus, Nullable<bool> isPaid, Nullable<int> createdBy)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var orderDateParameter = orderDate != null ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(string));
    
            var orderTypeParameter = orderType.HasValue ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(int));
    
            var diliveryTimeParameter = diliveryTime != null ?
                new ObjectParameter("DiliveryTime", diliveryTime) :
                new ObjectParameter("DiliveryTime", typeof(string));
    
            var totalAmountParameter = totalAmount.HasValue ?
                new ObjectParameter("TotalAmount", totalAmount) :
                new ObjectParameter("TotalAmount", typeof(int));
    
            var totalDueParameter = totalDue.HasValue ?
                new ObjectParameter("TotalDue", totalDue) :
                new ObjectParameter("TotalDue", typeof(int));
    
            var orderNoParameter = orderNo != null ?
                new ObjectParameter("OrderNo", orderNo) :
                new ObjectParameter("OrderNo", typeof(string));
    
            var shipViaParameter = shipVia != null ?
                new ObjectParameter("ShipVia", shipVia) :
                new ObjectParameter("ShipVia", typeof(string));
    
            var gSTApplyParameter = gSTApply.HasValue ?
                new ObjectParameter("GSTApply", gSTApply) :
                new ObjectParameter("GSTApply", typeof(int));
    
            var orderCommentsParameter = orderComments != null ?
                new ObjectParameter("OrderComments", orderComments) :
                new ObjectParameter("OrderComments", typeof(string));
    
            var freightchargeParameter = freightcharge.HasValue ?
                new ObjectParameter("freightcharge", freightcharge) :
                new ObjectParameter("freightcharge", typeof(int));
    
            var orderStatusParameter = orderStatus.HasValue ?
                new ObjectParameter("OrderStatus", orderStatus) :
                new ObjectParameter("OrderStatus", typeof(int));
    
            var isPaidParameter = isPaid.HasValue ?
                new ObjectParameter("IsPaid", isPaid) :
                new ObjectParameter("IsPaid", typeof(bool));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_InsertUpdateOrder", flagParameter, companyIdParameter, orderIDParameter, orderDateParameter, orderTypeParameter, diliveryTimeParameter, totalAmountParameter, totalDueParameter, orderNoParameter, shipViaParameter, gSTApplyParameter, orderCommentsParameter, freightchargeParameter, orderStatusParameter, isPaidParameter, createdByParameter);
        }
    
        public virtual int usp_InsertUpdateOrderDetail(string flag, Nullable<int> createdby, Nullable<int> orderID)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(int));
    
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertUpdateOrderDetail", flagParameter, createdbyParameter, orderIDParameter);
        }
    
        public virtual int usp_InsertUpdateOrderTransaction(string flag, Nullable<int> createdby)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertUpdateOrderTransaction", flagParameter, createdbyParameter);
        }
    
        public virtual int usp_InsertUpdateProduct(string flag, Nullable<int> productID, Nullable<int> productTypeId, string productSize, string productX, string productUw, string productGrade, string productCode, string productPhoto, Nullable<int> productPrice, string productCompany, string productAbrasive, Nullable<int> productWeight, string productQuality, string productMovement, Nullable<int> createdby)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var productTypeIdParameter = productTypeId.HasValue ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(int));
    
            var productSizeParameter = productSize != null ?
                new ObjectParameter("ProductSize", productSize) :
                new ObjectParameter("ProductSize", typeof(string));
    
            var productXParameter = productX != null ?
                new ObjectParameter("ProductX", productX) :
                new ObjectParameter("ProductX", typeof(string));
    
            var productUwParameter = productUw != null ?
                new ObjectParameter("ProductUw", productUw) :
                new ObjectParameter("ProductUw", typeof(string));
    
            var productGradeParameter = productGrade != null ?
                new ObjectParameter("ProductGrade", productGrade) :
                new ObjectParameter("ProductGrade", typeof(string));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var productPhotoParameter = productPhoto != null ?
                new ObjectParameter("ProductPhoto", productPhoto) :
                new ObjectParameter("ProductPhoto", typeof(string));
    
            var productPriceParameter = productPrice.HasValue ?
                new ObjectParameter("ProductPrice", productPrice) :
                new ObjectParameter("ProductPrice", typeof(int));
    
            var productCompanyParameter = productCompany != null ?
                new ObjectParameter("ProductCompany", productCompany) :
                new ObjectParameter("ProductCompany", typeof(string));
    
            var productAbrasiveParameter = productAbrasive != null ?
                new ObjectParameter("ProductAbrasive", productAbrasive) :
                new ObjectParameter("ProductAbrasive", typeof(string));
    
            var productWeightParameter = productWeight.HasValue ?
                new ObjectParameter("ProductWeight", productWeight) :
                new ObjectParameter("ProductWeight", typeof(int));
    
            var productQualityParameter = productQuality != null ?
                new ObjectParameter("ProductQuality", productQuality) :
                new ObjectParameter("ProductQuality", typeof(string));
    
            var productMovementParameter = productMovement != null ?
                new ObjectParameter("ProductMovement", productMovement) :
                new ObjectParameter("ProductMovement", typeof(string));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertUpdateProduct", flagParameter, productIDParameter, productTypeIdParameter, productSizeParameter, productXParameter, productUwParameter, productGradeParameter, productCodeParameter, productPhotoParameter, productPriceParameter, productCompanyParameter, productAbrasiveParameter, productWeightParameter, productQualityParameter, productMovementParameter, createdbyParameter);
        }
    
        public virtual int usp_InsertUpdateProductType(string flag, Nullable<int> productTypeId, string type, string productTypeName, string productTypeDetail, string frontImage, string diagramImage, string productTypeImage, Nullable<int> createdby)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var productTypeIdParameter = productTypeId.HasValue ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var productTypeNameParameter = productTypeName != null ?
                new ObjectParameter("ProductTypeName", productTypeName) :
                new ObjectParameter("ProductTypeName", typeof(string));
    
            var productTypeDetailParameter = productTypeDetail != null ?
                new ObjectParameter("ProductTypeDetail", productTypeDetail) :
                new ObjectParameter("ProductTypeDetail", typeof(string));
    
            var frontImageParameter = frontImage != null ?
                new ObjectParameter("FrontImage", frontImage) :
                new ObjectParameter("FrontImage", typeof(string));
    
            var diagramImageParameter = diagramImage != null ?
                new ObjectParameter("DiagramImage", diagramImage) :
                new ObjectParameter("DiagramImage", typeof(string));
    
            var productTypeImageParameter = productTypeImage != null ?
                new ObjectParameter("ProductTypeImage", productTypeImage) :
                new ObjectParameter("ProductTypeImage", typeof(string));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertUpdateProductType", flagParameter, productTypeIdParameter, typeParameter, productTypeNameParameter, productTypeDetailParameter, frontImageParameter, diagramImageParameter, productTypeImageParameter, createdbyParameter);
        }
    
        public virtual int usp_InsertUpdateWorkSheet(string flag, Nullable<int> workId, Nullable<int> companyId, string date, string description, string remark, Nullable<int> status, Nullable<int> createdBy)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var workIdParameter = workId.HasValue ?
                new ObjectParameter("WorkId", workId) :
                new ObjectParameter("WorkId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("Remark", remark) :
                new ObjectParameter("Remark", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertUpdateWorkSheet", flagParameter, workIdParameter, companyIdParameter, dateParameter, descriptionParameter, remarkParameter, statusParameter, createdByParameter);
        }
    
        public virtual ObjectResult<usp_GetOrderData_Result> usp_GetOrderData(string flag, Nullable<int> orderId)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(string));
    
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderData_Result>("usp_GetOrderData", flagParameter, orderIdParameter);
        }
    }
}
