//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string DiliveryTime { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> TotalDue { get; set; }
        public string OrderNo { get; set; }
        public string ShipVia { get; set; }
        public Nullable<int> GSTApply { get; set; }
        public string OrderComments { get; set; }
        public Nullable<int> freightcharge { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
    }
}
