//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public string ProductDetail { get; set; }
        public int Quantity { get; set; }
        public int ProductPrice { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public Nullable<int> RemainingQuantity { get; set; }
        public Nullable<int> OLDProductPrice { get; set; }
    }
}
