//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public int ProductTypeId { get; set; }
        public string Type { get; set; }
        public string ProductTypeName { get; set; }
        public string ProductTypeDetail { get; set; }
        public string FrontImage { get; set; }
        public string DiagramImage { get; set; }
        public string ProductTypeImage { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
    }
}
