//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public int ProductTypeId { get; set; }
        public string ProductSize { get; set; }
        public string ProductX { get; set; }
        public string ProductUw { get; set; }
        public string ProductGrade { get; set; }
        public string ProductCode { get; set; }
        public string ProductPhoto { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public string ProductCompany { get; set; }
        public string ProductAbrasive { get; set; }
        public Nullable<int> ProductWeight { get; set; }
        public string ProductQuality { get; set; }
        public string ProductMovement { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
    }
}
